-- 전체 스키마 (IF NOT EXISTS 기반 — 기존 환경에도 안전하게 적용됨)
CREATE EXTENSION IF NOT EXISTS vector;

-- ── 기본 참조 테이블 ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS area_code (
    area_code VARCHAR(5) PRIMARY KEY,
    name      VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS category (
    code        VARCHAR(12) PRIMARY KEY,
    depth       SMALLINT    NOT NULL,
    name        VARCHAR(100) NOT NULL,
    parent_code VARCHAR(12)
);

CREATE TABLE IF NOT EXISTS sigungu_code (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_code    VARCHAR(5)  NOT NULL,
    name         VARCHAR(50) NOT NULL,
    sigungu_code VARCHAR(5)  NOT NULL,
    CONSTRAINT uk_sigungu_area_code UNIQUE (area_code, sigungu_code)
);

-- ── 관광지 핵심 ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS tourist_spot (
    content_id        BIGINT PRIMARY KEY,
    addr1             VARCHAR(300),
    addr2             VARCHAR(200),
    collected_at      TIMESTAMP(6),
    created_time      TIMESTAMP(6),
    expguide          TEXT,
    first_image       TEXT,
    homepage          TEXT,
    infocenter        VARCHAR(200),
    map_level         SMALLINT,
    map_x             NUMERIC(13, 10),
    map_y             NUMERIC(13, 10),
    parking           TEXT,
    restdate          TEXT,
    sigungu_code      VARCHAR(5),
    title             VARCHAR(200) NOT NULL,
    usetime           TEXT,
    zipcode           VARCHAR(10),
    content_type_id   VARCHAR(5),
    ldong_regn_code   VARCHAR(5),
    ldong_signgu_code VARCHAR(5),
    category          INTEGER NOT NULL CHECK (category BETWEEN 1 AND 7),
    overview          TEXT,
    detail_info       JSONB    NOT NULL DEFAULT jsonb_build_array(),
    avg_rating        NUMERIC(3, 1) NOT NULL DEFAULT 0.0,
    review_count      INTEGER      NOT NULL DEFAULT 0
);

-- 기존 환경: 누락 컬럼 보강
ALTER TABLE tourist_spot
    ADD COLUMN IF NOT EXISTS content_type_id   VARCHAR(5),
    ADD COLUMN IF NOT EXISTS ldong_regn_code   VARCHAR(5),
    ADD COLUMN IF NOT EXISTS ldong_signgu_code VARCHAR(5),
    ADD COLUMN IF NOT EXISTS category          INTEGER,
    ADD COLUMN IF NOT EXISTS overview          TEXT,
    ADD COLUMN IF NOT EXISTS detail_info       JSONB NOT NULL DEFAULT jsonb_build_array(),
    ADD COLUMN IF NOT EXISTS avg_rating        NUMERIC(3, 1) NOT NULL DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS review_count      INTEGER       NOT NULL DEFAULT 0;

-- 기존 환경: avg_rating NUMERIC(3,2) → NUMERIC(3,1) 타입 변환
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'tourist_spot' AND column_name = 'avg_rating'
          AND numeric_scale = 2
    ) THEN
        ALTER TABLE tourist_spot ALTER COLUMN avg_rating TYPE NUMERIC(3,1) USING avg_rating::NUMERIC(3,1);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS spot_image (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT  NOT NULL,
    image_url  TEXT,
    "order"    INTEGER NOT NULL,
    CONSTRAINT uk_spot_image_content_order UNIQUE (content_id, "order")
);

-- ── 임베딩 / AI ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS spot_embedding (
    content_id   BIGINT PRIMARY KEY,
    created_at   TIMESTAMP(6),
    embedding    VECTOR(1536),
    input_text   TEXT,
    keyword_text TEXT
);

ALTER TABLE spot_embedding
    ADD COLUMN IF NOT EXISTS keyword_text TEXT;

-- 이전 스키마 잔재 제거 (kakao_spot_id 컬럼 및 관련 제약)
ALTER TABLE spot_embedding DROP CONSTRAINT IF EXISTS fk_spot_embedding_kakao;
ALTER TABLE spot_embedding DROP CONSTRAINT IF EXISTS chk_spot_embedding_source;
DROP INDEX IF EXISTS uk_spot_embedding_kakao;
DROP INDEX IF EXISTS uk_spot_embedding_content;
ALTER TABLE spot_embedding DROP COLUMN IF EXISTS kakao_spot_id;

-- embedding_id PK → content_id PK 복원 (구버전 스키마에서 마이그레이션된 경우)
DO $$
DECLARE current_pk TEXT;
BEGIN
    SELECT kcu.column_name INTO current_pk
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
        ON tc.constraint_name = kcu.constraint_name AND tc.table_name = kcu.table_name
    WHERE tc.table_name = 'spot_embedding' AND tc.constraint_type = 'PRIMARY KEY';
    IF current_pk = 'embedding_id' THEN
        ALTER TABLE spot_embedding DROP CONSTRAINT spot_embedding_pkey;
        ALTER TABLE spot_embedding DROP COLUMN embedding_id;
        ALTER TABLE spot_embedding ALTER COLUMN content_id SET NOT NULL;
        ALTER TABLE spot_embedding ADD CONSTRAINT spot_embedding_pkey PRIMARY KEY (content_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS spot_ai_recommendation (
    content_id      BIGINT       PRIMARY KEY REFERENCES tourist_spot(content_id) ON DELETE CASCADE,
    reason          TEXT         NOT NULL,
    prompt_version  VARCHAR(30)  NOT NULL,
    generated_at    TIMESTAMP(6) NOT NULL,
    expires_at      TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS spot_related_recommendation (
    content_id          BIGINT       PRIMARY KEY REFERENCES tourist_spot(content_id) ON DELETE CASCADE,
    related_content_ids TEXT         NOT NULL,
    scoring_version     VARCHAR(30)  NOT NULL,
    generated_at        TIMESTAMP(6) NOT NULL,
    expires_at          TIMESTAMP(6) NOT NULL
);

-- ── 인기도 / 통계 ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS spot_popularity (
    content_id       BIGINT           PRIMARY KEY,
    mention_score    DOUBLE PRECISION NOT NULL DEFAULT 0,
    popularity_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    category_rank    INTEGER,
    rank_tag         VARCHAR(30),
    calculated_at    TIMESTAMP(6)     NOT NULL DEFAULT now(),
    CONSTRAINT fk_spot_popularity_spot
        FOREIGN KEY (content_id) REFERENCES tourist_spot(content_id) ON DELETE CASCADE
);

-- ── ETL 상태 ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS etl_spot_state (
    content_id              BIGINT       PRIMARY KEY,
    embed_pending           BOOLEAN      NOT NULL DEFAULT true,
    last_etl_at             TIMESTAMP(6) NOT NULL DEFAULT now(),
    content_hash            VARCHAR(64)  NOT NULL DEFAULT '',
    image_pending           BOOLEAN      NOT NULL DEFAULT true,
    image_absent            BOOLEAN      NOT NULL DEFAULT false,
    detail_common_pending   BOOLEAN      NOT NULL DEFAULT true,
    detail_intro_pending    BOOLEAN      NOT NULL DEFAULT true,
    detail_info_pending     BOOLEAN      NOT NULL DEFAULT true,
    overview                TEXT
);

CREATE TABLE IF NOT EXISTS etl_run (
    run_id      VARCHAR(250) NOT NULL,
    dag_id      VARCHAR(250) NOT NULL,
    started_at  TIMESTAMP    NOT NULL DEFAULT now(),
    finished_at TIMESTAMP,
    status      VARCHAR(20)  NOT NULL DEFAULT 'running',
    stats       JSONB        NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (dag_id, run_id)
);

-- ── 리뷰 ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS review (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id      BIGINT        NOT NULL,
    user_id         BIGINT        NOT NULL,
    rating          NUMERIC(3,1)  NOT NULL CHECK (rating BETWEEN 1.0 AND 5.0),
    body            TEXT,
    is_deleted      BOOLEAN       NOT NULL DEFAULT FALSE,
    visit_type      VARCHAR(20)   NOT NULL DEFAULT 'GENERAL',
    gps_verified_at TIMESTAMP(6),
    created_at      TIMESTAMP(6)  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP(6),
    CONSTRAINT fk_review_spot   FOREIGN KEY (content_id) REFERENCES tourist_spot(content_id) ON DELETE CASCADE
);

-- 기존 환경: 누락 컬럼 보강
ALTER TABLE review
    ADD COLUMN IF NOT EXISTS visit_type      VARCHAR(20)  NOT NULL DEFAULT 'GENERAL',
    ADD COLUMN IF NOT EXISTS gps_verified_at TIMESTAMP(6);

-- 기존 환경: rating SMALLINT → NUMERIC(3,1) 타입 변환
DO $$
DECLARE v_constraint_name TEXT;
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'review' AND column_name = 'rating'
          AND data_type = 'smallint'
    ) THEN
        -- inline CHECK (rating BETWEEN 1 AND 5) 를 constraint 이름으로 찾아 제거
        SELECT con.conname INTO v_constraint_name
        FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        WHERE rel.relname = 'review'
          AND con.contype = 'c'
          AND pg_get_constraintdef(con.oid) LIKE '%rating%';

        IF v_constraint_name IS NOT NULL THEN
            EXECUTE 'ALTER TABLE review DROP CONSTRAINT ' || quote_ident(v_constraint_name);
        END IF;

        ALTER TABLE review ALTER COLUMN rating TYPE NUMERIC(3,1) USING rating::NUMERIC(3,1);
    END IF;
END $$;

-- CHECK constraint (IF NOT EXISTS 방어)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_review_visit_type') THEN
        ALTER TABLE review ADD CONSTRAINT chk_review_visit_type
            CHECK (visit_type IN ('GENERAL', 'GPS_VERIFIED'));
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_review_rating') THEN
        ALTER TABLE review ADD CONSTRAINT chk_review_rating
            CHECK (rating BETWEEN 0.1 AND 5.0);
    END IF;
END $$;

-- 소프트 딜리트 정합성: (content_id, user_id) 전체 유니크 → 활성 리뷰(is_deleted=false)만 유니크
-- 삭제 후 재작성 시 남아있는 soft-deleted 행 때문에 발생하던 uk_review_user_spot 위반 방지
ALTER TABLE review DROP CONSTRAINT IF EXISTS uk_review_user_spot;

CREATE UNIQUE INDEX IF NOT EXISTS uk_review_user_spot_active
    ON review (content_id, user_id) WHERE is_deleted = FALSE;

-- users FK: JPA가 앱 기동 시 users 테이블을 생성하므로 존재할 때만 추가
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'users'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'review' AND constraint_name = 'fk_review_user'
    ) THEN
        EXECUTE 'ALTER TABLE review ADD CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE';
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS review_image (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id     BIGINT       NOT NULL,
    image_url     TEXT         NOT NULL,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMP(6) NOT NULL DEFAULT now(),
    CONSTRAINT fk_review_image_review FOREIGN KEY (review_id) REFERENCES review(id) ON DELETE CASCADE,
    CONSTRAINT uk_review_image_order  UNIQUE (review_id, display_order)
);

-- ── 이전 스키마 불필요 테이블 / 컬럼 제거 ────────────────────────────────────

DROP INDEX IF EXISTS uk_like_user_kakao;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'spot_like'
    ) THEN
        EXECUTE 'ALTER TABLE spot_like DROP CONSTRAINT IF EXISTS fk_like_kakao';
        EXECUTE 'ALTER TABLE spot_like DROP CONSTRAINT IF EXISTS chk_like_source';
        EXECUTE 'DELETE FROM spot_like WHERE content_id IS NULL';
        EXECUTE 'ALTER TABLE spot_like DROP COLUMN IF EXISTS kakao_spot_id';
        EXECUTE 'ALTER TABLE spot_like ALTER COLUMN content_id SET NOT NULL';
    END IF;
END $$;

DROP TABLE IF EXISTS kakao_spot_image;
DROP TABLE IF EXISTS kakao_spot;
DROP TABLE IF EXISTS trending_spot;

-- ── 인덱스 ───────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_image_content                   ON spot_image (content_id);
CREATE INDEX IF NOT EXISTS idx_spot_category                   ON tourist_spot (category);
CREATE INDEX IF NOT EXISTS idx_spot_content_type               ON tourist_spot (content_type_id);
CREATE INDEX IF NOT EXISTS idx_spot_ldong_region               ON tourist_spot (ldong_regn_code, ldong_signgu_code);
CREATE INDEX IF NOT EXISTS idx_spot_sigungu                    ON tourist_spot (sigungu_code);
CREATE INDEX IF NOT EXISTS idx_state_image_recovery            ON etl_spot_state (content_id) WHERE image_absent = false;
CREATE INDEX IF NOT EXISTS idx_spot_popularity_score           ON spot_popularity (popularity_score DESC);
CREATE INDEX IF NOT EXISTS idx_spot_popularity_rank            ON spot_popularity (category_rank) WHERE category_rank IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_spot_ai_recommendation_expires  ON spot_ai_recommendation (expires_at);
CREATE INDEX IF NOT EXISTS idx_spot_related_recommendation_expires ON spot_related_recommendation (expires_at);
CREATE INDEX IF NOT EXISTS idx_spot_embedding_cosine ON spot_embedding
    USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_review_content                  ON review (content_id) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_review_user                     ON review (user_id)    WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_review_image_review             ON review_image (review_id);
